language: node_js
node_js:
  - "lts/*"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm update
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod  --base-href https://lukecmstevens.co.uk/quidditch-scotland/
  - npx ngh --dir=dist/quidditch-scotland --repo=https://GH_TOKEN@github.com/lukecmstevens/quidditch-scotland.git --name="Luke Stevens" --email=lcm.stevens96@gmail.com